mqtt:
  url: "tcp://24.199.80.14:1883"
  clientId: "spring-boot-client"
  defaultTopic: "/test/securify"

jwt:
  secret: "94c9b14f-b497-4f25-bc02-4f5e1a512c3d"
  exptime: 1296000000
  qr-expVisitortime: 180000
  qr-secret: "94d8b15f-b794-4f25-bc02-4f5h1a512c3d"
  qr-exptime: 300000

spring:
  sql:
    init:
      mode: always
  application:
    name: SecurifyServer
  mustache:
    suffix: .html
  datasource:
    url: jdbc:postgresql://localhost:5500/securifydb
    username: securifyuser
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
    show-sql: true
