jwt:
  secret: "NuevaClaveSecretaMuySegurade256bits"
  exptime: 1296000000

spring:
  sql:
    init:
      mode: always
  application:
    name: SecurifyServer
  mustache:
    suffix: .html
  datasource:
    url: jdbc:postgresql://localhost:5432/securifydb
    username: andres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
    show-sql: true
